"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { Activity, CheckCircle2, CircleAlert, Radio } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type MissionEvent = { type: string; message: string };

export default function MissionControlView() {
  const apiUrl = process.env.NEXT_PUBLIC_LINGO_API_URL || "http://localhost:8000";
  const [objective, setObjective] = useState("");
  const [market, setMarket] = useState("Dubai");
  const [audience, setAudience] = useState("");
  const [events, setEvents] = useState<MissionEvent[]>([]);
  const [summary, setSummary] = useState("");
  const [error, setError] = useState("");
  const [running, setRunning] = useState(false);
  const socket = useRef<WebSocket | null>(null);

  useEffect(() => () => socket.current?.close(), []);

  async function startMission(event: FormEvent) {
    event.preventDefault();
    setError(""); setSummary(""); setEvents([]); setRunning(true);
    try {
      const response = await fetch(`${apiUrl}/api/missions/market-launch`, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ objective, target_market: market, audience }),
      });
      if (!response.ok) throw new Error("Lingo could not start the mission.");
      const { mission_id } = await response.json();
      const wsUrl = `${apiUrl.replace(/^http/, "ws")}/api/missions/${mission_id}/events`;
      socket.current = new WebSocket(wsUrl);
      socket.current.onmessage = async ({ data }) => {
        const update = JSON.parse(data) as MissionEvent;
        setEvents((current) => [...current, update]);
        if (update.type === "mission.completed" || update.type === "mission.failed") {
          socket.current?.close(); setRunning(false);
          const result = await fetch(`${apiUrl}/api/missions/${mission_id}`);
          if (result.ok) setSummary((await result.json()).manager_summary);
        }
      };
      socket.current.onerror = () => { setError("Live updates disconnected. Refresh the mission to check its result."); setRunning(false); };
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Mission could not start."); setRunning(false); }
  }

  return <div className="h-full overflow-auto bg-stone-50 p-4 md:p-8">
    <div className="mx-auto max-w-6xl space-y-6">
      <div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-violet-700">Mission Control</p><h2 className="mt-1 text-2xl font-semibold tracking-tight text-stone-900">Turn a goal into reviewed action.</h2><p className="mt-2 max-w-2xl text-sm text-stone-600">Lingo shows live agent work, approvals, and outcomes. It never hides progress behind simulated thoughts.</p></div><div className="flex items-center gap-2 text-sm text-stone-600"><Radio className={running ? "h-4 w-4 text-violet-600" : "h-4 w-4"}/>{running ? "Live mission" : "Ready"}</div></div>
      <div className="grid gap-6 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]">
        <Card><CardHeader><CardTitle>Start a Market Launch</CardTitle><CardDescription>Begin with a concise business outcome. Lingo will ask for approval before any external action.</CardDescription></CardHeader><CardContent><form onSubmit={startMission} className="space-y-4"><Textarea required minLength={10} value={objective} onChange={(e) => setObjective(e.target.value)} placeholder="Example: Launch our sustainable skincare line in Dubai."/><Input required value={market} onChange={(e) => setMarket(e.target.value)} placeholder="Target market"/><Input required value={audience} onChange={(e) => setAudience(e.target.value)} placeholder="Target audience"/><Button type="submit" disabled={running} className="w-full bg-violet-700 hover:bg-violet-800">{running ? "Mission in progress" : "Start mission"}</Button></form></CardContent></Card>
        <Card><CardHeader><CardTitle>Live agent updates</CardTitle><CardDescription>Each event is generated by the backend workflow and can be audited later.</CardDescription></CardHeader><CardContent className="space-y-3">{events.length === 0 ? <p className="py-8 text-sm text-stone-500">Start a mission to see its timeline, evidence work, and approval requests here.</p> : events.map((item, index) => <div key={`${item.type}-${index}`} className="flex gap-3 border-b border-stone-100 pb-3 last:border-0"><Activity className="mt-0.5 h-4 w-4 text-violet-700"/><div><p className="text-sm font-medium text-stone-900">{item.type.replace(".", " ")}</p><p className="text-sm text-stone-600">{item.message}</p></div></div>)}{error && <p className="flex gap-2 text-sm text-red-700"><CircleAlert className="h-4 w-4"/>{error}</p>}{summary && <div className="rounded-lg bg-emerald-50 p-4 text-sm text-emerald-950"><p className="mb-2 flex items-center gap-2 font-medium"><CheckCircle2 className="h-4 w-4"/>Mission brief</p><p className="whitespace-pre-wrap">{summary}</p></div>}</CardContent></Card>
      </div>
    </div>
  </div>;
}
